[package]
name = "janki"
version = "0.1.0"
edition = "2021"
description = "Janky Anki"
license = "MIT"
readme = "README.md"
keywords = ["cli", "learning", "anki", "serde"]
categories = ["cli", "learning"]
repository = "https://github.com/Epacnoss/janki"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.31"
serde = {version = "1.0.139", features = ["derive"], optional = true}
serde_json = {version = "1.0.82", optional = true }

[features]
default = ["serde"]
file_storage = ["serde_json"]
serde_json = ["serde", "dep:serde_json"]
serde = ["dep:serde"]

[[bin]]
path = "src/cli/main.rs"
name = "janki_cli"
