[package]
name = "janki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = {version = "1.0.139", features = ["derive"]}
serde_json = "1.0.82"
thiserror = "1.0.31"

[features]
